### ISSUE TITLE
Wrong text on library.properties

### ISSUE THREAD

**Issue by crushedice2000** [arduino-libraries/Keyboard#1]
Hi!

In the fifth line of `library.properties` says this:

> For Leonardo/Micro only

I think that this text is wrong because this may work in another platforms.

If this is an outdated text, please update it. Else please explain me why this text is correct.

Best regards.

Helio.

**Comment by facchinm** [comment]
Fixed, thanks!

**Comment by crushedice2000** [comment]
@facchinm You're welcome!
