### ISSUE TITLE
How to update the installed library to this version?

### ISSUE THREAD

**Issue by zagatozee** [arduino-libraries/Keyboard#16]
I'm trying to get a sketch working that will allow the f13-f24 keys working, but I can't get the library manager to update to this version of the files, if I try to add the zip of these files via "manage libraries" I get the error; "A library named Keyboard-master already exists".

I can't manually replace the default ones the IDE uses because that folder is protected by windows.

So, can I get the library manager to read these files as a valid update, or somehow tell the IDE to ignore the default libraries and read these ones instead? Or do I just need to wait for the IDE to update to these versions?

Currently using "Arduino 1.8.5 (Windows Store 1.8.10.0)"

**Comment by facchinm** [comment]
@zagatozee sorry, I forgot to push the update, doing it now (the update will be available in a couple of hours, no need to download the library as zip).
Anyway, if you want to test a library which has not been released yet, you need to manually remove the folder  `C:\Users\YourUsername\Arduino\$LibraryName` to make sure there are no clashes. That folder is not protected and always takes precedence over the one bundled with the IDE.

**Comment by zagatozee** [comment]
Was able to update (v1.0.2) and now the keyboard.h shows the f13-f24 keys - thankyou. Issue closed.
