### ISSUE TITLE
are imposible print a  "@"

### ISSUE THREAD

**Issue by ArielBaravalle** [arduino-libraries/Keyboard#20]
Hello
Please,  confirm how this is possible ,  I try different ways with bad result .
thanks and regards

**Comment by ArielBaravalle** [comment]
Sorry,  I resolve now  :)

```
    Keyboard.press(KEY_LEFT_CTRL);         // send Hex value for RETURN key
    Keyboard.press(KEY_LEFT_ALT);         // send Hex value for RETURN key
    delay(500);
    Keyboard.write(50); 
    Keyboard.releaseAll();
```

**Comment by Abh15h3k** [comment]
if u want yo print '@' symbol just do

Keyboard.press(KEY_LEFT_SHIFT);
Keyboard.press('2');
delay(100);
Keyboard.releaseAll();

**Comment by mo-pyy** [comment]
I have the same problem and I am using a German Keyboard Layout. Normally we press AltGreat and "q", but there is no AltGreat Modifier implemented. The Method using CTRL + ALT + "q" is only working on windows, but I am under linux. Any suggestions?

**Comment by thekunalsaini** [comment]
You can use english keyboard @ArielBaravalle

**Comment by James-Livesey** [comment]
@mo-pyy I believe that Alt Graph (Alt Gr) is exactly the same as Right Alt.

So to enter an `@` symbol on a German keyboard, use the following code:

```c++
Keyboard.press(KEY_RIGHT_ALT);
Keyboard.press("q");
delay(100);
Keyboard.releaseAll();
```

**Comment by edgar-bonet** [comment]
This issue has been fixed. Since version 1.0.3, this library supports the German keyboard layout. Initialize it like this:

```c++
Keyboard.begin(KeyboardLayout_de_DE);
```

Then you can type `@` with:

```c++
Keyboard.write('@');
```

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino-libraries/Keyboard/pull/53
Thanks @edgar-bonet!
