### ISSUE TITLE
Only available for qwerty

### ISSUE THREAD

**Issue by DapfiDuck** [arduino-libraries/Keyboard#21]
This is infact a very useful library but it only works for qwerty keyboards. If you e.g. work with a qwertzu keyboard it fails at the special characters.

**Comment by facchinm** [comment]
@DapfiDuck for special keyboard layouts I always suggest https://github.com/NicoHood/HID . This library has been kept simple by design so it will never support advanced features.

**Comment by DapfiDuck** [comment]
> @DapfiDuck for special keyboard layouts I always suggest https://github.com/NicoHood/HID . This library has been kept simple by design so it will never support advanced features.

I converted to forking and working on it myself. But thank you for the link :)
