### ISSUE TITLE
How to print bslash 

### ISSUE THREAD

**Issue by ArduinoMasterInfernal** [arduino-libraries/Keyboard#23]
hi, i'm trying to print bslash ( \ )

i have try many syntax but it not work, do you know what to forget?
```c++
#include <Keyboard.h>

char altKey = KEY_RIGHT_ALT;

void setup() {
  Keyboard.begin();
}

void loop() {
  delay(5000);
  Keyboard.press(altKey);
  Keyboard.press(38);
  delay(100);
  Keyboard.press(0x26);
  Keyboard.releaseAll();
  Keyboard.print("005C");
  Keyboard.write(92);
  Keyboard.write(0x5C);
  Keyboard.write(38);
  Keyboard.write(49);
  // wait for new window to open:
  delay(1000);
}
```

**Comment by ArduinoMasterInfernal** [comment]
i have an azerty keyboard i also try use  : https://github.com/martin-leo/KeyboardAzertyFr

i got same error : arduino leonardo print : àà(C**7&

**Comment by edgar-bonet** [comment]
This issue has been fixed. Since version 1.0.3, this library supports the French keyboard layout. Initialize it like this:

```c++
Keyboard.begin(KeyboardLayout_fr_FR);
```

Then you can type `\` with:

```c++
Keyboard.write('\');
```
