### ISSUE TITLE
when I use Keyboard.h, could I press keycode instead of keyASCII？

### ISSUE THREAD

**Issue by ljq29** [arduino-libraries/Keyboard#26]
It is generally accepted that when the header file Keyboard.h is used, some control keys can be sent through the Keyboard.press (key) function. But for keys without ASCII values, such as KEYCODE_VOLUME_UP and KEYCODE_VOLUME_DOWN, how should they be sent to the host through arduino?

**Comment by anaicagrouver** [comment]
0x80	Keyboard Volume Up
0x81	Keyboard Volume Down
0x7F	Keyboard Mute
You can also see the list [here](https://www.arduino.cc/en/Reference/KeyboardModifiers)

**Comment by thekunalsaini** [comment]
@ljq29  you can use hex codes for this

**Comment by ljq29** [comment]
> @ljq29 you can use hex codes for this

So, from where I can find the table of keycode 2 hex?

**Comment by thekunalsaini** [comment]
@ljq29  Google it man it is easily available

**Comment by thekunalsaini** [comment]
If @ljq29 you are satisfied give a good feedback ;)

**Comment by edgar-bonet** [comment]
Closing this as a duplicate of issue #17.
