### ISSUE TITLE
"Keyboard not found, Does your sketch include the line #include <Keyboard.h>"

### ISSUE THREAD

**Issue by kiranshashiny** [arduino-libraries/Keyboard#39]
How do I resolve this error on Arduino IDE.

I installed the library and do find it in Arduino IDE.

I'm unable to compile it for Arduino Uno.
This is on Mac OS - High Sierra 10.13.6
I want to use it for testing IR receiver hardware.

![image](https://user-images.githubusercontent.com/14288989/88763473-d0650a80-d190-11ea-9143-b6e5aba81df1.png)

![image](https://user-images.githubusercontent.com/14288989/88763509-e246ad80-d190-11ea-8c70-584b91c0e091.png)

![image](https://user-images.githubusercontent.com/14288989/88763359-a57ab680-d190-11ea-86a6-8dbba6d8ac84.png)

**Comment by kiranshashiny** [comment]
There is a Keyboard.h in the /Users/Myname/Documents/Arduino/libraries/Keyboard-master/src folder

$ find . -name Keyboard.h -print
./src/Keyboard.h

**Comment by facchinm** [comment]
The Keyboard library is only suitable for boards with native USB (eg. Micro, Leonardo, all the MKR), so trying to compile on the Uno will not work.

**Comment by kiranshashiny** [comment]
Oh ! 
So let my Issue be there - do not 'Remove. So others who encounter such an issue will know about it.

Regards, Shashi 

    On Wednesday, July 29, 2020, 01:25:43 PM GMT+5:30, Martino Facchin <notifications@github.com> wrote:  
 
 


The Keyboard library is only suitable for boards with native USB (eg. Micro, Leonardo, all the MKR), so trying to compile on the Uno will not work.

**Comment by joex92** [comment]
wait, what about the MEGA 2560 R3?

**Comment by per1234** [comment]
@joex92 please post on the Arduino forum if you would like assistance using your Mega 2560 R3 board or this library:

https://forum.arduino.cc/
