### ISSUE TITLE
LED status (Capslock, Numlock, Scrollock)

### ISSUE THREAD

**Issue by mic159** [arduino-libraries/Keyboard#6]
I was wondering if it would be possible to get the state of these flags from the OS?

I found a patch on this forum post: http://forum.arduino.cc/index.php?topic=173583.msg1474558#msg1474558
Its outdated, and I cant figure out how to send the data from HID -> Keyboard now that they are separate.

I was wondering if you had any ideas on how best to bridge the gap?
Should I just `#include "Keyboard.h"` inside HID.cpp, or should there be some callback you can register in HID, then Keyboard reads the message and decodes the LED status from there.

**Comment by facchinm** [comment]
Hi @mic159 , you can safely use https://github.com/NicoHood/HID library if you want more control on Keyboard entities. By separating keyboard from HID core you now have the chance to use/write functions integrated with the USB core via external libraries, so mainline Keyboard and Mouse will not receive functionality updates.
