### ISSUE TITLE
In Italian Layout < and \ are swapped

### ISSUE THREAD

**Issue by RobertoD91** [arduino-libraries/Keyboard#72]
**Hardware:**
The Atmega32u4 inside the WHID https://github.com/whid-injector/WHID

**Software:**
Arduino IDE 1.8.19
Keyboard Library 1.0.4

Simple test program:
```
#include "Keyboard.h"

void setup() {
  Serial.begin(9600);
  Keyboard.begin(KeyboardLayout_it_IT);
}

void loop() {
  if (Serial.available() > 0) {
    char inChar = Serial.read();
    Serial.print("hai inviato: ");
    Serial.println(inChar);
    Keyboard.write(inChar);
  }
}
```

**Issue:**
the character `<` is replaced with `\` and viceversa
also `>` is replaced with `|`and viceversa

**Fix?**
edit the file in `Documents/Arduino/libraries/Keyboard/src/KeyboardLayout_it_IT.cpp`
replacing `0x32` with `0x35` and viceversa

I don't have another hardware for testing, i don't know if the problem is in the library or in the WHID.

**Comment by edgar-bonet** [comment]
I cannot reproduce the issue.

First of all, I must admit that I wrote this layout file without having ever touche an Italian keyboard. That being said, all the sources I found online (e.g. [1][], [2][], [3][], [4][], [5][]) agree on this:

* the key <kbd>&lt;&gt;</kbd> is in the lower-left corner of the keyboard, between <kbd>Shift</kbd> and <kbd>Z</kbd>

* the key <kbd>\\|</kbd> is in the top-left corner, right next to <kbd>1!</kbd>

Is that the case with the keyboard you are using?

I tried your test program, after setting my keyboard layout to Italian (as known by my Ubuntu OS). When I type `<`, `>`, `\` and `|`, I do get the same characters echoed back by my Micro.

[1]: http://kbd-intl.narod.ru/english/layouts
[2]: http://kbdlayout.info/kbdit
[3]: https://docs.microsoft.com/en-us/globalization/keyboards/kbdit.html
[4]: https://upload.wikimedia.org/wikipedia/commons/e/e5/Italian_Keyboard_layout.svg
[5]: https://sites.google.com/site/brightmeasurement/Home/keyboard-for-english-around-the-word

**Comment by RobertoD91** [comment]
Sorry, my fault. I had accidentally set the keyboard as ANSI instead of ISO on all my computer (it wasn't a system-wide setting).

The library is ok, tested with WHID and Arduino Yun.

Sorry
