### ISSUE TITLE
Support for Portuguese (pt_PT) keyboard layout

### ISSUE THREAD

**Issue by danielalexis** [arduino-libraries/Keyboard#76]
Is support for layouts for other languages coming ?

**Comment by per1234** [comment]
Are there specific languages you would like to request be added @danielalexis?

**Comment by danielalexis** [comment]
Portuguese (pt_PT) as there as some issues even using es_ES.

A quarta, 19/10/2022, 13:03, per1234 ***@***.***> escreveu:
