### ISSUE TITLE
Multiple language layout support

### ISSUE THREAD

**Issue by ernesto-xload** [arduino-libraries/Keyboard#8]
Hello,

I modified this library to support other keyboard layouts, I think that would be good merge this version.

I uploaded to: https://github.com/ernesto-xload/arduino_keyboardlib

Best regads

**Comment by facchinm** [comment]
Hi @ernesto-xload ,
thanks for contributing. We are trying to keep the library as small as possible, while giving the chance to anyone (thanks to the HID subsystem) to replace it with another library. Feel free to propose yours for inclusion in the LibraryManager following the guidelines reported [here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ). Thanks again!
