### ISSUE TITLE
Analog reading

### ISSUE THREAD

**Issue by TERM4X** [arduino-libraries/Keyboard#80]
Is there a way to send a command to the pc with a scale of values?

Example:
send the key "B" with 50% intensity, or the key "A" with 25% intensity, resulting in the character in a game goes at 25% speed instead of alswais 100%

**Comment by per1234** [comment]
Hi @TERM4X. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
