### ISSUE TITLE
Using analog A6, A7 on Nano

### ISSUE THREAD

**Issue by svatoun** [arduino-libraries/Keyboard#9]
The specification says that A6, A7 on Arduino Nano can only be used for analog inputs. Indeed, when I (not reading thoroughly the ATMEL spec) used A6, A7 as rows in Keypad setup, the whole sketch stopped to work (even reading from read digital inputs).

However if the HW provides pull-up resistors, even A6, A7 can be used as rows in the keypad matrix input, at the cost of some ifs in pin_mode etc. I'll prepare subclass of Keypad to allow for processing analog inputs.

**Comment by facchinm** [comment]
Hi @svatoun ,
this library is intended to be used with boards with native USB chips. The Nano doesn't have such capabilities, so probably you are referring to another library. 
I'm closing this issue as invalid, if you want to post here the URL of the library you are referring to I can give some hints on where to report the bug. Thanks!

**Comment by svatoun** [comment]
Oh my. Apologies,  keypad != keyboard ... sorry for the confusion, I filed the issue into an incorrect project.
