### ISSUE TITLE
where is the key of "space"?

### ISSUE THREAD

**Issue by zhjygit** [arduino-libraries/Keyboard#92]
now, there is only key_backspace, however there is no space(null key or blank key)

**Comment by edgar-bonet** [comment]
Try this:

```c++
Keyboard.write(' ');
```

In the line above, note the space between the single quote characters.

**Comment by zhjygit** [comment]
> Try this:
> 
> ```c++
> Keyboard.write(' ');
> ```
> 
> In the line above, note the space between the single quote characters.

Thanks sir, I did as above some days ago.
Thank you all the same.
